# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Informática Básica
#
# @author Abolaji Ibidokun Steven alu0101619613@ull.edu.es
# @date Nov 4 2024
# @brief Makefile file for the video tutorial
# 
# @see 

all: compile link

compile:
	g++ -c change_case_main.cc

link:
	g++ -o change_case_main change_case_main.o

clean:
	rm -f *.o change_case_main*~
